package fr.ensisa.hassenforder.transportation.kiosk.ui;

import java.util.Enumeration;

import javax.swing.AbstractButton;

import fr.ensisa.hassenforder.transportation.kiosk.model.ModelListener;
import fr.ensisa.hassenforder.transportation.kiosk.model.Pass;
import fr.ensisa.hassenforder.transportation.kiosk.model.Ticket;

/**
 *
 * @author hassenforder
 */
public class Kiosk_UI extends javax.swing.JFrame implements ModelListener {

    private GUIListener listener;

    /**
     * Creates new form Kiosk_UI
     */
    public Kiosk_UI() {
        initComponents();
    }

    public void setListener(GUIListener listener) {
        this.listener = listener;
    }
    
    @Override
    public void notifyStatusChanged (String status) {
        jStatus.setText(status);
    }

    @Override
    public void notifyClientChanged (long passId) {
    	if (passId == -1L) jClientID.setText("");
    	else jClientID.setText(Long.toString(passId));
    }

    @Override
    public void notifyPassChanged (Pass pass) {
		jTravels.removeAll();
		jSubscriptions.removeAll();
    	if (pass == null) {
    		jClientDescription.setText("");
    	} else {
    		jClientDescription.setText(pass.getDescription());
    		for (Ticket t : pass.getTickets()) {
				switch (t.getType()) {
				case ROUTE :
					jTravels.add(new RouteComponent(t, null));
					break;
				case URBAN :
					jTravels.add(new UrbanComponent(t, null));
					break;
				case SUBSCRIPTION :
					jSubscriptions.add(new SubscriptionComponent(t, null));
					break;
				}
    		}
    	}
		jTravels.revalidate();
		jTravels.repaint();        
		jSubscriptions.revalidate();
		jSubscriptions.repaint();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        month = new javax.swing.ButtonGroup();
        urban = new javax.swing.ButtonGroup();
        route = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jFrom1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTo1 = new javax.swing.JComboBox<>();
        jTravelOneWay1 = new javax.swing.JRadioButton();
        jTravelRoundTrip1 = new javax.swing.JRadioButton();
        jTravelMultiple1 = new javax.swing.JRadioButton();
        jTravelCount1 = new javax.swing.JTextField();
        jRouteBuy1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTravelOneWay = new javax.swing.JRadioButton();
        jTravelRoundTrip = new javax.swing.JRadioButton();
        jTravelMultiple = new javax.swing.JRadioButton();
        jTravelCount = new javax.swing.JTextField();
        jRouteBuy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jClientID = new javax.swing.JTextField();
        jClientFetch = new javax.swing.JButton();
        jClientDescription = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTravels = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jSubscriptions = new javax.swing.JPanel();
        jCreate = new javax.swing.JButton();
        jStatus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jRouteBuy2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kiosk");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Route");

        jFrom1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        		"Altkirch", "Bâle", "Belfort", "Cernay", "Colmar", "Mulhouse", "Saint Louis", "Strasbourg", "Thann"
    		}));

        jLabel9.setText("From");

        jLabel10.setText("To");

        jTo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        		"Altkirch", "Bâle", "Belfort", "Cernay", "Colmar", "Mulhouse", "Saint Louis", "Strasbourg", "Thann"
    		}));

        route.add(jTravelOneWay1);
        jTravelOneWay1.setText("One Way");

        route.add(jTravelRoundTrip1);
        jTravelRoundTrip1.setText("Round Trip");

        route.add(jTravelMultiple1);
        jTravelMultiple1.setText("Multiple");

        jTravelCount1.setText("0");

        jRouteBuy1.setText("Buy");
        jRouteBuy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRouteBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTravelOneWay1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(39, 39, 39)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTravelRoundTrip1)
                                .addGap(18, 18, 18)
                                .addComponent(jTravelMultiple1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTravelCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRouteBuy1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRouteBuy1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTravelOneWay1)
                    .addComponent(jTravelRoundTrip1)
                    .addComponent(jTravelMultiple1)
                    .addComponent(jTravelCount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Urban");

        urban.add(jTravelOneWay);
        jTravelOneWay.setText("One Way");

        urban.add(jTravelRoundTrip);
        jTravelRoundTrip.setText("Round Trip");

        urban.add(jTravelMultiple);
        jTravelMultiple.setText("Multiple");

        jTravelCount.setText("0");

        jRouteBuy.setText("Buy");
        jRouteBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUrbanBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRouteBuy))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTravelOneWay)
                        .addGap(11, 11, 11)
                        .addComponent(jTravelRoundTrip)
                        .addGap(18, 18, 18)
                        .addComponent(jTravelMultiple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTravelCount, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRouteBuy)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTravelOneWay)
                    .addComponent(jTravelRoundTrip)
                    .addComponent(jTravelMultiple)
                    .addComponent(jTravelCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Client");

        jClientID.setText("1");
        jClientID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jClientIDKeyTyped(evt);
            }
        });

        jClientFetch.setText("Fetch");
        jClientFetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientFetchActionPerformed(evt);
            }
        });

        jClientDescription.setText("ClientDescription");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Travels");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTravels.setLayout(new javax.swing.BoxLayout(jTravels, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jTravels);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Subscriptions");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jSubscriptions.setLayout(new javax.swing.BoxLayout(jSubscriptions, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(jSubscriptions);

        jCreate.setText("Create");
        jCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jClientDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jClientID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jClientFetch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCreate)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClientFetch)
                    .addComponent(jCreate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClientDescription)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jStatus.setText("status");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Subscription");

        jRouteBuy2.setText("Buy");
        jRouteBuy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubscriptionBuyActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new java.awt.GridLayout(3, 4));

        month.add(jRadioButton1);
        jRadioButton1.setText("January");
        jPanel5.add(jRadioButton1);

        month.add(jRadioButton2);
        jRadioButton2.setText("February");
        jPanel5.add(jRadioButton2);

        month.add(jRadioButton3);
        jRadioButton3.setText("March");
        jPanel5.add(jRadioButton3);

        month.add(jRadioButton4);
        jRadioButton4.setText("April");
        jPanel5.add(jRadioButton4);

        month.add(jRadioButton5);
        jRadioButton5.setText("May");
        jPanel5.add(jRadioButton5);

        month.add(jRadioButton6);
        jRadioButton6.setText("June");
        jPanel5.add(jRadioButton6);

        month.add(jRadioButton7);
        jRadioButton7.setText("July");
        jPanel5.add(jRadioButton7);

        month.add(jRadioButton8);
        jRadioButton8.setText("August");
        jPanel5.add(jRadioButton8);

        month.add(jRadioButton9);
        jRadioButton9.setText("September");
        jPanel5.add(jRadioButton9);

        month.add(jRadioButton10);
        jRadioButton10.setText("October");
        jPanel5.add(jRadioButton10);

        month.add(jRadioButton11);
        jRadioButton11.setText("November");
        jPanel5.add(jRadioButton11);

        month.add(jRadioButton12);
        jRadioButton12.setText("December");
        jPanel5.add(jRadioButton12);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jRouteBuy2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jRouteBuy2))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jStatus))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateActionPerformed
    	if (listener != null) listener.onClickCreatePass ();
    }//GEN-LAST:event_jCreateActionPerformed

    private void jClientFetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientFetchActionPerformed
    	long passId = 0;
    	try { passId = Long.parseLong(jClientID.getText()); } catch (Exception e) { }
    	if (listener != null) listener.onClickFetch(passId);
    }//GEN-LAST:event_jClientFetchActionPerformed

    private void jClientIDKeyTyped(java.awt.event.KeyEvent evt) {                                   
    	if (evt.getKeyChar() == '\n') {
        	int passId = 0;
        	try { passId = Integer.parseInt(jClientID.getText()); } catch (Exception e) { }
        	if (listener != null) listener.onClickFetch(passId);
    	}
    }                                  

    private void jRouteBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRouteBuyActionPerformed
    	long passId = -1;
    	try { passId = Long.parseLong(jClientID.getText()); } catch (Exception e) { }
    	String from = (String) jFrom1.getSelectedItem();
    	String to = (String) jTo1.getSelectedItem();
    	int count = 0;
    	Enumeration<AbstractButton> eabs = route.getElements();
    	while (eabs.hasMoreElements()) {
    		AbstractButton ab = eabs.nextElement();
    		if (ab.isSelected()) {
    			if (ab == jTravelOneWay1) count = 1;
    			if (ab == jTravelRoundTrip1) count = 2;
    			if (ab == jTravelMultiple1) {
    		    	try { count = Integer.parseInt(jTravelCount1.getText()); } catch (Exception e) { }
    			}
    		}
    	}
    	if (from == null || from.equals("")) {
    		jStatus.setText("From is not well");
    		return;
    	}
    	if (to == null || to.equals("")) {
    		jStatus.setText("To is not well");
    		return;
    	}
    	if (count == 0) {
    		jStatus.setText("Ways is wrong");
    		return;
    	}
    	if (listener != null) listener.onClickBuyRoute (passId, from, to, count);
    }//GEN-LAST:event_jRouteBuyActionPerformed

    private void jUrbanBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUrbanBuyActionPerformed
    	long passId = -1;
    	try { passId = Long.parseLong(jClientID.getText()); } catch (Exception e) { }
    	int count = 0;
    	Enumeration<AbstractButton> eabs = urban.getElements();
    	while (eabs.hasMoreElements()) {
    		AbstractButton ab = eabs.nextElement();
    		if (ab.isSelected()) {
    			if (ab == jTravelOneWay) count = 1;
    			if (ab == jTravelRoundTrip) count = 2;
    			if (ab == jTravelMultiple) {
    		    	try { count = Integer.parseInt(jTravelCount.getText()); } catch (Exception e) { }
    			}
    		}
    	}
    	if (count == 0) {
    		jStatus.setText("Ways is wrong");
    		return;
    	}
    	if (listener != null) listener.onClickBuyUrban (passId, count);
    }//GEN-LAST:event_jUrbanBuyActionPerformed

    private void jSubscriptionBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubscriptionBuyActionPerformed
    	long passId = -1;
    	try { passId = Long.parseLong(jClientID.getText()); } catch (Exception e) { }
    	Enumeration<AbstractButton> eabs = month.getElements();
    	int month = -1;
    	int crt = 0;
    	while (eabs.hasMoreElements()) {
    		AbstractButton ab = eabs.nextElement();
    		if (ab.isSelected()) month = crt;
    		++crt;
    	}
    	if (month == -1) {
    		jStatus.setText("Month is wrong");
    		return;
    	}
    	if (listener != null) listener.onClickBuySubscription (passId, month);
    }//GEN-LAST:event_jSubscriptionBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kiosk_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kiosk_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kiosk_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kiosk_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kiosk_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jClientDescription;
    private javax.swing.JButton jClientFetch;
    private javax.swing.JTextField jClientID;
    private javax.swing.JButton jCreate;
    private javax.swing.JComboBox<String> jFrom1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JButton jRouteBuy;
    private javax.swing.JButton jRouteBuy1;
    private javax.swing.JButton jRouteBuy2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jStatus;
    private javax.swing.JPanel jSubscriptions;
    private javax.swing.JComboBox<String> jTo1;
    private javax.swing.JTextField jTravelCount;
    private javax.swing.JTextField jTravelCount1;
    private javax.swing.JRadioButton jTravelMultiple;
    private javax.swing.JRadioButton jTravelMultiple1;
    private javax.swing.JRadioButton jTravelOneWay;
    private javax.swing.JRadioButton jTravelOneWay1;
    private javax.swing.JRadioButton jTravelRoundTrip;
    private javax.swing.JRadioButton jTravelRoundTrip1;
    private javax.swing.JPanel jTravels;
    private javax.swing.ButtonGroup month;
    private javax.swing.ButtonGroup route;
    private javax.swing.ButtonGroup urban;
    // End of variables declaration//GEN-END:variables
}
