package fr.ensisa.hassenforder.transportation.terminal.ui;

import fr.ensisa.hassenforder.transportation.terminal.model.Ticket;

/**
 *
 * @author hassenforder
 */
public class RouteComponent extends javax.swing.JPanel {

    private GUIListener listener;
    private Ticket ticket;

    /**
     * Creates new form RouteComponent
     */
    public RouteComponent(Ticket ticket, GUIListener listener) {
        initComponents();
        this.ticket = ticket;
        this.listener = listener;
        updateView ();
    }

    public void updateView () {
        jFrom.setText(ticket.getFrom());
        jTo.setText(ticket.getTo());
        jCount.setText(Integer.toString(ticket.getCount()));
        jUsed.setText(Integer.toString(ticket.getUsed()));
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrom = new javax.swing.JLabel();
        jTo = new javax.swing.JLabel();
        jUsed = new javax.swing.JLabel();
        jCount = new javax.swing.JLabel();
        jUse = new javax.swing.JButton();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(380, 25));
        setMinimumSize(new java.awt.Dimension(380, 25));
        setPreferredSize(new java.awt.Dimension(380, 25));

        jFrom.setText("from");

        jTo.setText("to");

        jUsed.setText("used");
        jUsed.setMaximumSize(new java.awt.Dimension(16, 16));
        jUsed.setMinimumSize(new java.awt.Dimension(16, 16));

        jCount.setText("count");

        jUse.setText("Use");
        jUse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUse))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUse)
                    .addComponent(jCount)
                    .addComponent(jFrom)
                    .addComponent(jTo)
                    .addComponent(jUsed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUseActionPerformed
        if (listener != null) listener.onClickTicketUse(ticket, 1);
    }//GEN-LAST:event_jUseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jFrom;
    private javax.swing.JLabel jCount;
    private javax.swing.JLabel jTo;
    private javax.swing.JButton jUse;
    private javax.swing.JLabel jUsed;
    // End of variables declaration//GEN-END:variables
}
